version: '3'
services:
  web:
    build: .
    image: rust-webapp:latest
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /usr/src/rust-webapp/src
        - action: rebuild
          path: ./Cargo.toml
          target: /usr/src/rust-webapp/Cargo.toml
        - action: sync
          path: .env
          target: /var/www/rust-webapp/.env
    env_file:
      - .env
    ports:
      - "80:${ROCKET_PORT}"