version: '3'
services:
  web:
    build: ./
    image: rust-webapp:latest
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /usr/src/rust-webapp/src
    ports:
      - "80:8080"